CREATE DATABASE DbAlgoritmoGenetico;

CREATE TABLE TB_PROFESSOR (
	IdProfessor SERIAL PRIMARY KEY,
	Nome VARCHAR(50)
);

CREATE TABLE TB_DISCIPLINA (
	IdDisciplina SERIAL PRIMARY KEY,
	Nome VARCHAR(50),
	Periodo INTEGER,
	IdProfessor SERIAL,
	FOREIGN KEY (IdProfessor) REFERENCES TB_PROFESSOR (IdProfessor)
);

CREATE TABLE TB_ANO (
	IdAno SERIAL PRIMARY KEY,
	Periodo VARCHAR(10), -- 20201, 20202 (2020.2)
	Tipo VARCHAR(5) -- impar, par
);

CREATE TABLE TB_RESTRICAO (
	IdRestricao SERIAL PRIMARY KEY,
	Segunda BOOLEAN,
	Terca BOOLEAN,
	Quarta BOOLEAN,
	Quinta BOOLEAN,
	Sexta BOOLEAN,
	IdAno SERIAL,
	IdProfessor SERIAL,
	FOREIGN KEY (IdAno) REFERENCES TB_ANO (IdAno),
	FOREIGN KEY (IdProfessor) REFERENCES TB_PROFESSOR (IdProfessor)
);

CREATE TABLE TB_HORARIO (
	IdHorario SERIAL PRIMARY KEY,
	IdAno SERIAL,
	IdDisciplina SERIAL,
	FOREIGN KEY (IdAno) REFERENCES TB_ANO (IdAno),
	FOREIGN KEY (IdDisciplina) REFERENCES TB_DISCIPLINA (IdDisciplina)
);

CREATE TABLE TB_RESTRICAO_HORARIO(
	IdRestricaoHorario SERIAL PRIMARY KEY,
	Segunda1 BOOLEAN,
	Segunda2 BOOLEAN,
	Segunda3 BOOLEAN,
	Terca1 BOOLEAN,
	Terca2 BOOLEAN,
	Terca3 BOOLEAN,
	Quarta1 BOOLEAN,
	Quarta2 BOOLEAN,
	Quarta3 BOOLEAN,
	Quinta1 BOOLEAN,
	Quinta2 BOOLEAN,
	Quinta3 BOOLEAN,
	Sexta1 BOOLEAN,
	Sexta2 BOOLEAN,
	Sexta3 BOOLEAN,
	Periodo INTEGER,
	IdAno SERIAL,
	FOREIGN KEY (IdAno) REFERENCES TB_ANO (IdAno)
);